export const noteActionTypes = {
    
    FETCH_REQUEST:  'FETCH_NOTES_REQUEST',
    FETCH_SUCCESS: 'FETCH_NOTES_SUCCESS',
    FETCH_FAILURE: 'FETCH_NOTES_FAILURE',

    CREATE_REQUEST:  'CREATE_NOTE_REQUEST',
    CREATE_SUCCESS: 'CREATE_NOTE_SUCCESS',
    CREATE_FAILURE: 'CREATE_NOTE_FAILURE',

    EDIT_REQUEST:  'EDIT_NOTE_REQUEST',
    EDIT_SUCCESS: 'EDIT_NOTE_SUCCESS',
    EDIT_FAILURE: 'EDIT_NOTE_FAILURE',

    DELETE_REQUEST:  'DELETE_NOTE_REQUEST',
    DELETE_SUCCESS: 'DELETE_NOTE_SUCCESS',
    DELETE_FAILURE: 'DELETE_NOTE_FAILURE'
    
}